# Generated by Django 3.1.2 on 2020-10-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='Unique_ID',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Unique_SquirrelID',
            field=models.CharField(blank=True, help_text='unique squirrel id of squirrel', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], help_text='age of squirrel', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='mmddyyyy'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(help_text='latitude of squirrel', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(help_text='longitude of squirrel', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='shift of squirrel', max_length=100),
        ),
    ]
