# Generated by Django 3.1.2 on 2020-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20201020_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='shift of squirrel', max_length=100),
        ),
    ]
