# Generated by Django 3.1.2 on 2020-10-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20201020_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], help_text='Please select', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(help_text='To eight decimal places', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(help_text='To eight decimal places', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Please select', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_SquirrelID',
            field=models.CharField(blank=True, help_text='Hectare-Shift-mmdd-Hectare Squirrel Number. e.g. "37F-PM-1014-03"', max_length=100, null=True, unique=True),
        ),
    ]
