# Generated by Django 3.1.2 on 2020-10-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20201021_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel approaches you'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel is chasing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel is climbing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel is eating'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel is foraging'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel is indifferent to you'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel kuks'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel moans'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.TextField(blank=True, help_text='Describe the specific activity'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Primary_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Grey', 'Grey'), ('Cinnamon', 'Cinnamon')], help_text='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel quaas'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel is running'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(default=False, help_text='Whether or not the squirrel runs from you'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.TextField(blank=True, help_text='Describe the specific location'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Flags',
            field=models.BooleanField(default=False, help_text='Whether or not the tail flags'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Twitches',
            field=models.BooleanField(default=False, help_text='Whether or not the tail twitches'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', 'Unknown')], default='Unknown', help_text='Please select', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='*yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(help_text='*To eight decimal places', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(help_text='*To eight decimal places', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='*Please select', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_SquirrelID',
            field=models.CharField(blank=True, help_text='*Hectare-Shift-mmdd-Hectare Squirrel Number. e.g. "37F-PM-1014-03"', max_length=100, null=True, unique=True),
        ),
    ]
