# Generated by Django 3.1.2 on 2020-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20201021_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], help_text='Please select', max_length=100, null=True),
        ),
    ]
